### ISSUE TITLE
Schema based on an `Enum` in `pydantic` fails for `None` type

### ISSUE THREAD

**Issue by MrCreosote** [mnboos/jsonschema-default#10]
Hi, firstly thanks very much for the time you've spent on this library, it was exactly what I was looking for. 

I have a use case where I want to create a dict containing the default values from a `pydantic` model that contains an `enum`. However, the schema that `pydantic` produces seems to be incompatible with `jsonschema_default`:

```python
import enum
import json
import jsonschema_default
from pydantic import BaseModel, Field


class Thing(str, enum.Enum):
    FOO = "foo"
    BAR = "bar"


class Container(BaseModel):
    thing: Thing = Field(default=Thing.FOO)


schema = Container.schema()
print(json.dumps(schema, indent=2))

jsonschema_default.create_from(schema)
```

That produces the output:
```
{
  "title": "Container",
  "type": "object",
  "properties": {
    "thing": {
      "default": "foo",
      "allOf": [
        {
          "$ref": "#/definitions/Thing"
        }
      ]
    }
  },
  "definitions": {
    "Thing": {
      "title": "Thing",
      "description": "An enumeration.",
      "enum": [
        "foo",
        "bar"
      ],
      "type": "string"
    }
  }
}
Traceback (most recent call last):
  File "<root>/src/test.py", line 19, in <module>
    jsonschema_default.create_from(schema)
  File "<home>/.local/share/virtualenvs/collections-Ov35wl3J/lib/python3.11/site-packages/jsonschema_default/__init__.py", line 28, in create_from
    obj = {p: _get_default(name=p, prop=prop, schema=schema) for p, prop in properties.items()}
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<home>/.local/share/virtualenvs/collections-Ov35wl3J/lib/python3.11/site-packages/jsonschema_default/__init__.py", line 28, in <dictcomp>
    obj = {p: _get_default(name=p, prop=prop, schema=schema) for p, prop in properties.items()}
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<home>/.local/share/virtualenvs/collections-Ov35wl3J/lib/python3.11/site-packages/jsonschema_default/__init__.py", line 63, in _get_default
    raise RuntimeError(f"Property '{name}' has an invalid type: {prop_type}")
RuntimeError: Property 'thing' has an invalid type: None
```

I'm guessing the `$ref` isn't being followed here?

Thanks for any help you can provide

**Comment by mnboos** [comment]
Hi and thanks for opening a ticket

I'm currently ill and will look into it, as soon as I'm well again.

So far. Cheers. 
Martin

**Comment by MrCreosote** [comment]
I'm sorry to hear that; I hope you feel better soon

**Comment by mnboos** [comment]
Thank you. So, after rewriting this library, [your test](https://github.com/mnboos/jsonschema-default/commit/8e0bf58d2902788474a1acf7e35e5423600ebdac) succeeds.

However, probably it's not what you would expect I guess. It now just uses the default `foo`.

**Comment by MrCreosote** [comment]
Awesome, thanks very much. 

> However, probably it's not what you would expect I guess. It now just uses the default `foo`.

That's what I would expect - I'm not sure what else the value could be. In case I'm missing something, what did you think I would expect as the result?

Thanks again

**Comment by mnboos** [comment]
I thought based on your question, you want the ref to be followed.

**Comment by MrCreosote** [comment]
Oh, I see. No, my thinking was along the lines of that the error stated the code was looking for the `type` field, which could only be found by following the `$ref`. I don't actually care whether the `$ref` is followed or not as long as the code succeeds.

Thanks again for the fix

**Comment by mnboos** [comment]
👍️
