### ISSUE TITLE
[feature request] Resolvers

### ISSUE THREAD

**Issue by cwiede** [mnboos/jsonschema-default#4]
It would be nice to add support for resolvers as supported by jsonschema. Not sure if there is an easy workaround for schemas containing references.

**Comment by mnboos** [comment]
Hi and thanks for your request!

Are you referring to this: https://json-schema.org/understanding-json-schema/structuring.html#ref ?

Some ref support is already implemented, please have a look at [the testing schemas](https://github.com/mnboos/jsonschema-default/tree/dev/schemas/ref).

I'm happy to support and implement other features, please provide some more details :)

**Comment by mnboos** [comment]
Hey @cwiede: Is this still relevant to you?

**Comment by cwiede** [comment]
thanks for asking - not really. I have worked around it now. Everything seems to work for me :) I think the issue can be closed.

**Comment by mnboos** [comment]
Okay. If anything pops up, don't hesitate to open another one.
