### ISSUE TITLE
Schema's with const also need a default value in the schema otherwise the default isn't created

### ISSUE THREAD

**Issue by ninloot** [mnboos/jsonschema-default#8]
If I have the following schema:
`{'$schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object', 'properties': {'id': {'type': 'string', 'const': 'vect3' }, 'x': {'type': 'number'} } }`
When the default json object is created, it creates an object line this:
`{ 'id': '', 'x': 0 }`
Since this object doesn't have the const value it's invalid. So in my opinion, the const value should be used as the default. I can certainly provide a default here as well but that just seems redundant.

**Comment by mnboos** [comment]
You're right, that's incorrect. I will fix it.
